# encoding: utf-8
    open('./tonguess/usable_select_3letters_words.txt', 'w'){|f|
    26.times do |num1|
      str1 = nil
      case num1
      when 0 then
        str1 = 'A'
      when 1 then
        str1 = 'B'
      when 2 then
        str1 = 'C'
      when 3 then
        str1 = 'D'
      when 4 then
        str1 = 'E'
      when 5 then
        str1 = 'F'
      when 6 then
        str1 = 'G'
      when 7 then
        str1 = 'H'
      when 8 then
        str1 = 'I'
      when 9 then
        str1 = 'J'
      when 10 then
        str1 = 'K'
      when 11 then
        str1 = 'L'
      when 12 then
        str1 = 'M'
      when 13 then
        str1 = 'N'
      when 14 then
        str1 = 'O'
      when 15 then
        str1 = 'P'
      when 16 then
        str1 = 'Q'
      when 17 then
        str1 = 'R'
      when 18 then
        str1 = 'S'
      when 19 then
        str1 = 'T'
      when 20 then
        str1 = 'U'
      when 21 then
        str1 = 'V'
      when 22 then
        str1 = 'W'
      when 23 then
        str1 = 'X'
      when 24 then
        str1 = 'Y'
      when 25 then
        str1 = 'Z'
      end
      26.times do |num2|
        case num2
        when 0 then
          str2 = "#{str1}A"
        when 1 then
          str2 = "#{str1}B"
        when 2 then
          str2 = "#{str1}C"
        when 3 then
          str2 = "#{str1}D"
        when 4 then
          str2 = "#{str1}E"
        when 5 then
          str2 = "#{str1}F"
        when 6 then
          str2 = "#{str1}G"
        when 7 then
          str2 = "#{str1}H"
        when 8 then
          str2 = "#{str1}I"
        when 9 then
          str2 = "#{str1}J"
        when 10 then
          str2 = "#{str1}K"
        when 11 then
          str2 = "#{str1}L"
        when 12 then
          str2 = "#{str1}M"
        when 13 then
          str2 = "#{str1}N"
        when 14 then
          str2 = "#{str1}O"
        when 15 then
          str2 = "#{str1}P"
        when 16 then
          str2 = "#{str1}Q"
        when 17 then
          str2 = "#{str1}R"
        when 18 then
          str2 = "#{str1}S"
        when 19 then
          str2 = "#{str1}T"
        when 20 then
          str2 = "#{str1}U"
        when 21 then
          str2 = "#{str1}V"
        when 22 then
          str2 = "#{str1}W"
        when 23 then
          str2 = "#{str1}X"
        when 24 then
          str2 = "#{str1}Y"
        when 25 then
          str2 = "#{str1}Z"
        end
        26.times do |num|
          case num
          when 0 then
            str = "#{str2}A"
          when 1 then  
            str = "#{str2}B"
          when 2 then
            str = "#{str2}C"
          when 3 then
            str = "#{str2}D"
          when 4 then
            str = "#{str2}E"
          when 5 then
            str = "#{str2}F"
          when 6 then
            str = "#{str2}G"
          when 7 then
            str = "#{str2}H"
          when 8 then
            str = "#{str2}I"
          when 9 then
            str = "#{str2}J"
          when 10 then
            str = "#{str2}K"
          when 11 then
            str = "#{str2}L"
          when 12 then
            str = "#{str2}M"
          when 13 then
            str = "#{str2}N"
          when 14 then
            str = "#{str2}O"
          when 15 then
            str = "#{str2}P"
          when 16 then
            str = "#{str2}Q"
          when 17 then
            str = "#{str2}R"
          when 18 then
            str = "#{str2}S"
          when 19 then
            str = "#{str2}T"
          when 20 then
            str = "#{str2}U"
          when 21 then
            str = "#{str2}V"
          when 22 then
            str = "#{str2}W"
          when 23 then
            str = "#{str2}X"
          when 24 then
            str = "#{str2}Y"
          when 25 then
            str = "#{str2}Z"
          end
          if str.slice(0) != str.slice(1) and str.slice(1) != str.slice(2) and str.slice(2) != str.slice(0)
            f.puts str
          end
        end
      end
    end
    }
