source 'https://rubygems.org'

gem 'rails', '>= 5.2.6'
# Use Puma as the app server
gem 'puma', '5.6.2'
# Use SCSS for stylesheets
gem 'sass-rails', '6.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'pry-rails', '0.3.9'
gem 'uglifier', '4.2.0'
# Use jquery as the JavaScript library
gem 'jquery-rails', '4.4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'bcrypt', '3.1.16'
gem 'turbolinks', '5.2.1'

gem 'actionview', '>= 5.2.4.4'

group :development, :test do
  gem 'byebug', '11.1.3', platform: :mri
  gem 'sqlite3', '1.4.2'

  gem 'listen', '3.4.1'
  gem 'web-console', '3.4.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '2.1.1'
  gem 'spring-watcher-listen', '2.0.1'
end
