source 'https://rubygems.org'

gem 'rails', '>= 5.2.4'
# Use Puma as the app server
gem 'puma', '4.3.12'
# Use SCSS for stylesheets
gem 'sass-rails', '5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'pry-rails', '0.3.4'
gem 'uglifier', '3.0.4'
# Use jquery as the JavaScript library
gem 'jquery-rails', '4.2.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'bcrypt', '3.1.11'
gem 'turbolinks', '5.0.1'

gem 'web-console', '3.4.0', group: :development

group :development, :test do
  gem 'byebug', '9.0.6', platform: :mri
  gem 'sqlite3', '1.4.2'

  gem 'listen', '3.0.8'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'rspec-rails', '3.5.1'
  gem 'spring', '2.0.1'
  gem 'spring-watcher-listen', '2.0.1'
end
